### ISSUE TITLE
Missing repository for ffmpeg

### ISSUE THREAD

**Issue by psychemedia** [kevinhughes27/audiogrep-docker#1]
I substituted `ppa:mc3man/trusty-media` via [How to install FFmpeg on Ubuntu 14.04](http://www.faqforge.com/linux/how-to-install-ffmpeg-on-ubuntu-14-04/]) and it seemed to install.

**Comment by kevinhughes27** [comment]
ah cool this is probably out of date now. Feel free to make a PR
